modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="fatedice"
version="1.0.3"
displayName="Fate Dice: Roll of Destiny"
authors="Developer"
description='''
Fate Dice: a mystical twenty-sided die (D20) featuring unpredictable events, reward tiers, and critical rolls!
'''

[[dependencies.fatedice]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.fatedice]]
modId="minecraft"
type="required"
versionRange="[1.21.1, 1.22)"
ordering="NONE"
side="BOTH"
